// Event context for the logged-in admin
export type EventContext = {
    eventName: string;
    adminEmail: string;
};

export type RootStackParamList = {
    Login: undefined;
    Home: undefined;
    Registration: {
        prefilledUID?: string;
        prefilledName?: string;
        prefilledEmail?: string;
        prefilledPhone?: string;
        prefilledCollege?: string;
        prefilledDept?: string;
        prefilledYear?: string;
    } | undefined;
    QRScanner: {
        mode?: 'INDIVIDUAL' | 'TEAM';
        teamSize?: number;
        teamName?: string; // Add team name parameter
    } | undefined;
    DatabaseViewer: undefined;
    RecentRegistrations: undefined;
    Export: undefined;
    Import: undefined;
    Search: undefined;
    TeamScannerSetup: undefined;
    OnSpotRegistration: undefined;
};

// Participant data structure matching Firebase schema
export interface Participant {
    uid: string;
    event_id: string;
    name: string;
    email: string;
    phone: string;
    college: string;
    college_other: string;
    degree: string;
    degree_other: string;
    department: string;
    department_other: string;
    year: string;
    checked_in: number;
    checkin_time: string | null;
    source: 'WEB' | 'ONSPOT';
    sync_status: number;
    payment_verified: number;
    participated: number;
}

// Year options
export const YEARS = ['Year 1', 'Year 2', 'Year 3', 'Year 4'];

// Degree options
export const DEGREES = [
    'B.Tech',
    'B.E',
    'B.Sc',
    'B.Com',
    'B.Arch',
    'M.Tech',
    'M.E',
    'MBA',
    'MCA',
    'Other'
];

// Department options
export const DEPARTMENTS = [
    'Artificial Intelligence and Data Science',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science and Business Systems',
    'Computer Science and Design',
    'Computer Science and Engineering',
    'CSE (Artificial Intelligence and Machine Learning)',
    'CSE (Cyber Security)',
    'Electrical and Electronics Engineering',
    'Electronics and Communication Engineering',
    'Mechanical Engineering',
    'Mechatronics Engineering',
    'Information Technology',
    'Other'
];

// College options for dropdown
export const COLLEGES = [
    'University Departments of Anna University Chennai - CEG Campus',
    'University Departments of Anna University Chennai - ACT Campus',
    'School of Architecture and Planning Anna University',
    'University Departments of Anna University Chennai - MIT Campus',
    'Annamalai University Faculty of Engineering and Technology',
    'Indian Institute of Information Technology Design & Manufacturing',
    'Indian Institute of Information Technology Tiruchirappalli',
    'Indian Institute of Technology Madras',
    'National Institute of Technology, Tiruchirappalli',
    'Academy of Maritime Education and Training',
    'Amrita Vishwa Vidyapeetham',
    'Avinashilingam Institute for Home Science & Higher Education for Women',
    'Bharath Institute of Higher Education & Research',
    'Chennai Mathematical Institute',
    'Chettinad Academy of Research and Education (CARE)',
    'Dr. M.G.R. Educational and Research Institute',
    'Hindustan Institute of Technology and Science (HITS)',
    'Kalasalingam Academy of Research and Education',
    'Karpagam Academy of Higher Education',
    'Karunya Institute of Technology and Sciences',
    'Meenakshi Academy of Higher Education and Research',
    'Noorul Islam Centre for Higher Education',
    'Periyar Maniammai Institute of Science & Technology',
    'Ponnaiyah Ramajayam Institute of Science & technology (PMIST)',
    'S.R.M. Institute of Science and Technology',
    'Sathyabama Institute of Science and Technology',
    'Saveetha Institute of Medical and Technical Sciences',
    'Shanmugha Arts, Science, Technology & Research Academy (SASTRA)',
    'Sri Chandrasekharandra Saraswati Vishwa Mahavidyalaya',
    'Sri Ramachandra Institute of Higher Education and Research',
    'St. Peter\'s Institute of Higher Education and Research',
    'The Gandhigram Rural Institute',
    'Vel Tech Rangarajan Dr Sagunthala R&D Institute of Science & Technology',
    'Vellore Institute of Technology',
    'Vels Institute of Science, Technology & Advanced Studies (VISTAS)',
    'Vinayaka Mission\'s Research Foundation',
    'University College of Engineering Villupuram',
    'University College of Engineering Tindivanam',
    'University College of Engineering Arni',
    'University College of Engineering Kancheepuram',
    'Aalim Muhammed Salegh College of Engineering',
    'Jaya Engineering College',
    'Jaya Institute of Technology',
    'Prathyusha Engineering college (Autonomous)',
    'R M D Engineering College (Autonomous)',
    'R M Engineering College (Autonomous)',
    'S A Engineering College (Autonomous)',
    'Sri Ram Engineering College',
    'Sri Venkateswara College of Engineering and Technology',
    'Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunthala Engineering College (Autonomous)',
    'Velammal Engineering College (Autonomous)',
    'Sri Venkateswara Institute of Science and Technology',
    'Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College (Autonomous)',
    'Gojan School of Business and Technology',
    'SAMS College of Engineering and Technology',
    'PMR Engineering College',
    'J N N Institute of Engineering (Autonomous)',
    'St. Peters College of Engineering and Technology',
    'R M K College of Engineering and Technology (Autonomous)',
    'Annai Veilankannis College of Engineering',
    'Annai Mira College of Engineering and Technology',
    'Jeppiaar Institute of Technology',
    'St. Joseph\'s Institute of Technology (Autonomous)',
    'Sri Jayaram Institute of Engineering and Technology',
    'D M I College of Engineering',
    'Kings Engineering College',
    'Pallavan College of Engineering',
    'Panimalar Engineering College (Autonomous)',
    'Rajalakshmi Engineering College (Autonomous)',
    'Rajiv Gandhi College of Engineering',
    'S K R Engineering College',
    'Saveetha Engineering College (Autonomous)',
    'Sree Sastha Institute of Engineering and Technology',
    'Sri Muthukumaran Institute of Technology',
    'Sri Venkateswara College of Engineering (Autonomous)',
    'Jaya College of Engineering and Technology',
    'P B College of Engineering',
    'Loyola Institute of Technology',
    'P T Lee Chengalvaraya Naicker College of Engineering and Technology',
    'Alpha College of Engineering',
    'Indira Institute of Engineering and Technology',
    'Apollo Engineering College',
    'A R M College of Engineering and Technology',
    'Adhi College of Engineering and Technology',
    'Jei Mathaajee College of Engineering',
    'Velammal Institute of Technology',
    'G R T Institute of Engineering and Technology',
    'T J S Engineering College',
    'Madha Institute of Engineering and Technology',
    'Mohammed Sathak A J College of Engineering',
    'Anand Institute of Higher Technology',
    'Easwari Engineering College (Autonomous)',
    'Jeppiaar Engineering College',
    'Jerusalem College of Engineering (Autonomous)',
    'Meenakshi Sundararajan Engineering College',
    'Misrimal Navajee Munoth Jain Engineering College',
    'K C G College of Technology (Autonomous)',
    'Shree Motilal Kanhaiyalal (SMK) Fomra Institute of Technology',
    'Sri Sivasubramaniya Nadar College of Engineering (Autonomous)',
    'Agni College of Technology',
    'St. Joseph\'s College of Engineering (Autonomous)',
    'T.J Institute of Technology',
    'Thangavelu Engineering College',
    'Central Institute of Petrochemicals Engineering and Technology (CIPET)',
    'Dhanalakshmi Srinivasan College of Engineering and Technology',
    'Sri Sai Ram Institute of Technology (Autonomous)',
    'St. Joseph College of Engineering',
    'ARS College of Engineering',
    'Sri Krishna Institute of Technology',
    'Chennai Institute of Technology and Applied Research',
    'Chennai Institute of Technology (Autonomous)',
    'Adhiparasakthi Engineering College',
    'Annai Teresa College of Engineering',
    'Dhanalakshmi College of Engineering',
    'G K M College of Engineering and Technology',
    'I F E T College of Engineering (Autonomous)',
    'Karpaga Vinayaga College of Engineering and Technology',
    'Madha Engineering College',
    'Mailam Engineering College',
    'Sri Venkateswaraa College of Technology',
    'Prince Shri Venkateshwara Padmavathy Engineering College (Autonomous)',
    'T S M Jain College of Technology',
    'Jaya Sakthi Engineering College',
    'Sri Sai Ram Engineering College (Autonomous)',
    'Tagore Engineering College',
    'V R S College of Engineering and Technology',
    'SRM Valliammai Engineering College (Autonomous)',
    'Asan Memorial College of Engineering and Technology',
    'Dhaanish Ahmed College of Engineering',
    'Sri Ramanujar Engineering College',
    'Sri Krishna Engineering College',
    'E S College of Engineering and Technology',
    'Maha Bharathi Engineering College',
    'New Prince Shri Bhavani College of Engineering and Technology (Autonomous)',
    'Rajalakshmi Institute of Technology (Autonomous)',
    'Surya Group of Institutions',
    'A R Engineering College',
    'Rrase College of Engineering',
    'Sree Krishna College of Engineering',
    'A K T Memorial College of Engineering and Technology',
    'Prince Dr. K Vasudevan College of Engineering and Technology',
    'Chendu College of Engineering and Technology',
    'Sri Rangapoopathi College of Engineering',
    'Saraswathy College of Engineering and Technology',
    'Loyola ICAM College of Engineering and Technology',
    'PERI Institute of Technology',
    'Adhiparasakthi College of Engineering',
    'Arulmigu Meenakshi Amman College of Engineering',
    'Arunai Engineering College',
    'C Abdul Hakeem College of Engineering and Technology',
    'Ganadipathy Tulsi\'s Jain Engineering College',
    'Meenakshi College of Engineering',
    'Priyadarshini Engineering College',
    'Ranipettai Engineering College',
    'S K P Engineering College',
    'Sri Balaji Chockalingam Engineering College',
    'Sri Nandhanam College of Engineering and Technology',
    'Thanthai Periyar Government Institute of Technology',
    'Thirumalai Engineering College',
    'Thiruvalluvar College of Engineering and Technology',
    'Bharathidasan Engineering College',
    'Kingston Engineering College',
    'Global Institute of Engineering and Technology',
    'Annamalaiar College of Engineering',
    'Podhigai College of Engineering and Technology',
    'Sri Krishna College of Engineering',
    'Oxford College of Engineering',
    'Idhaya Engineering College for Women',
    'Government College of Technology (Autonomous), Coimbatore',
    'PSG College of Technology (Autonomous)',
    'Coimbatore Institute of Technology (Autonomous)',
    'Anna University Regional Campus - Coimbatore',
    'Sri Shanmugha College of Engineering and Technology',
    'Muthayammal College of Engineering',
    'N S N College of Engineering and Technology',
    'K S R Institute for Engineering and Technology (Autonomous)',
    'Rathinam Technical Campus (Autonomous)',
    'Aishwarya College of Engineering and Technology',
    'Asian College of Engineering and Technology',
    'Ganesh College of Engineering',
    'Sri Ranganathar Institute of Engineering and Technology',
    'Indian Institute of Handloom Technology',
    'Dhirajlal Gandhi College of Technology',
    'Shree Sathyam College of Engineering and Technology',
    'AVS College of Technology',
    'Dhaanish Ahmed Institute of Technology',
    'Jairupaa College of Engineering',
    'Pollachi Institute of Engineering and Technology',
    'Arulmurugan College of Engineering',
    'V S B College of Engineering Technical Campus',
    'Suguna College of Engineering',
    'Arjun College of Technology',
    'Vishnu Lakshmi College of Engineering and Technology',
    'Government College of Engineering Dharmapuri',
    'PSG Institute of Technology and Applied Research',
    'Cherraan College of Technology',
    'Adhiyamaan College of Engineering (Autonomous)',
    'Annai Mathammal Sheela Engineering College',
    'Government College of Engineering (Autonomous) Bargur Krishnagiri District',
    'K S Rangasamy College of Technology (Autonomous)',
    'M Kumarasamy College of Engineering (Autonomous)',
    'Mahendra Engineering College (Autonomous)',
    'Muthayammal Engineering College (Autonomous)',
    'Paavai Engineering College (Autonomous)',
    'P G P College of Engineering and Technology',
    'K S R College of Engineering (Autonomous)',
    'S S M College of Engineering',
    'Government College of Engineering (Autonomous) Karuppur Salem District',
    'Sapthagiri College of Engineering',
    'Sengunthar Engineering College (Autonomous)',
    'Sona College of Technology (Autonomous)',
    'Vivekanandha College of Engineering for Women (Autonomous)',
    'Er. Perumal Manimekalai College of Engineering (Autonomous)',
    'V S B Engineering College (Autonomous)',
    'Mahendra College of Engineering',
    'Gnanamani College of Technology (Autonomous)',
    'The Kavery Engineering College',
    'Selvam College of Technology',
    'Paavai College of Engineering',
    'Chettinad College of Engineering and Technology',
    'Mahendra Institute of Technology (Autonomous)',
    'Vidyaa Vikas College of Engineering and Technology',
    'Excel Engineering College (Autonomous)',
    'CMS College of Engineering',
    'A V S Engineering College',
    'Mahendra Engineering College for Women',
    'R P Sarathy Institute of Technology',
    'Jayalakshmi Institute of Technology',
    'Varuvan Vadivelan Institute of Technology',
    'P S V College of Engineering and Technology',
    'Bharathiyar Institute of Engineering for Women',
    'Tagore Institute of Engineering and Technology',
    'J K K Nataraja College of Engineering and Technology',
    'Annapoorana Engineering College (Autonomous)',
    'Christ The King Engineering College',
    'Jai Shriram Engineering College',
    'AL-Ameen Engineering College (Autonomous)',
    'Knowledge Institute of Technology (Autonomous) KIOT Campus',
    'Builders Engineering College',
    'V S A Group of Institutions',
    'Salem College of Engineering and Technology',
    'Vivekanandha College of Technology for Women',
    'Sree Sakthi Engineering College',
    'Shreenivasa Engineering College',
    'Bannari Amman Institute of Technology (Autonomous)',
    'Coimbatore Institute of Engineering and Technology (Autonomous)',
    'CSI College of Engineering',
    'Dr. Mahalingam College of Engineering and Technology (Autonomous)',
    'Erode Sengunthar Engineering College (Autonomous)',
    'Hindusthan College of Engineering and Technology (Autonomous)',
    'Government College of Engineering (Formerly IRTT)',
    'Karpagam College of Engineering (Autonomous)',
    'Kongu Engineering College (Autonomous)',
    'Kumaraguru College of Technology (Autonomous)',
    'M P Nachimuthu M Jaganathan Engineering College',
    'Nandha Engineering College (Autonomous)',
    'Park College of Engineering and Technology',
    'Sasurie College of Engineering',
    'Sri Krishna College of Engineering and Technology (Autonomous)',
    'Sri Ramakrishna Engineering College (Autonomous)',
    'Tamilnadu College of Engineering Karumathampatti',
    'Sri Krishna College of Technology (Autonomous)',
    'Velalar College of Engineering and Technology (Autonomous)',
    'Sri Ramakrishna Institute of Technology (Autonomous)',
    'SNS College of Technology (Autonomous)',
    'Sri Shakthi Institute of Engineering and Technology (Autonomous)',
    'Nehru Institute of Engineering and Technology',
    'R V S College of Engineering and Technology',
    'Info Institute of Engineering',
    'Angel College of Engineering and Technology',
    'SNS College of Engineering (Autonomous)',
    'Karpagam Institute of Technology',
    'Dr. N G P Institute of Technology (Autonomous)',
    'Sri Sai Ranganathan Engineering College',
    'Sri Eshwar College of Engineering (Autonomous)',
    'Hindusthan Institute of Technology (Autonomous)',
    'P A College of Engineering and Technology (Autonomous)',
    'Dhanalakshmi Srinivasan College of Engineering (CBE)',
    'Adithya Institute of Technology',
    'Kathir College of Engineering',
    'Shree Venkateshwara Hi-Tech Engineering College (Autonomous)',
    'Surya Engineering College',
    'Easa College of Engineering and Technology',
    'KIT - Kalaignar Karunanidhi Institute of Technology (Autonomous)',
    'KGISL Institute of Technology KGISL Campus',
    'Nandha College of Technology',
    'PPG Institute of Technology',
    'Nehru Institute of Technology (Autonomous)',
    'J K K Munirajah College of Technology',
    'United Institute of Technology',
    'Jansons Institute of Technology',
    'Akshaya College of Engineering and Technology',
    'K P R Institute of Engineering and Technology (Autonomous)',
    'SRG Engineering College',
    'Park College of Technology',
    'J C T College of Engineering and Technology',
    'Studyworld College of Engineering',
    'C M S College of Engineering and Technology',
    'R V S Technical Campus-Coimbatore',
    'University College of Engineering Tiruchirappalli',
    'University College of Engineering Ariyalur',
    'University College of Engineering Nagappattinam',
    'University College of Engineering Kumbakonam',
    'University College of Engineering Thanjavur',
    'Mahalakshmi Engineering College Trichy-Salem',
    'Krishnasamy College of Engineering and Technology',
    'C K College of Engineering and Technology',
    'Sri Ramakrishna College of Engineering',
    'K S K College of Engineering and Technology',
    'Surya College of Engineering',
    'Arifa Institute of Technology',
    'Ariyalur Engineering College',
    'Government College of Engineering Gandarvakotta',
    'Government College of Engineering Srirangam',
    'Nelliandavar Institute of Technology',
    'K Ramakrishnan College of Technology (Autonomous)',
    'Sir Issac Newton College of Engineering and Technology',
    'Star Lion College of Engineering and Technology',
    'OASYS Institute of Technology',
    'M.A.M. School of Engineering',
    'SRM TRP Engineering College',
    'A V C College of Engineering',
    'Shri Angalamman College of Engineering and Technology',
    'Anjalai Ammal Mahalingam Engineering College',
    'Arasu Engineering College',
    'Dhanalakshmi Srinivasan Engineering College',
    'E G S Pillay Engineering College (Autonomous)',
    'J J College of Engineering and Technology',
    'Jayaram College of Engineering and Technology',
    'Kurinji College of Engineering and Technology',
    'M.A.M. College of Engineering',
    'M I E T Engineering College',
    'Mookambigai College of Engineering',
    'Oxford Engineering College',
    'P R Engineering College',
    'Pavendar Bharathidasan College of Engineering and Technology',
    'Roever Engineering College',
    'Saranathan College of Engineering',
    'Trichy Engineering College',
    'A R J College of Engineering and Technology',
    'Dr.Navalar Nedunchezhiyan College of Engineering',
    'St. Joseph\'s College of Engineering and Technology',
    'Kongunadu College of Engineering and Technology (Autonomous)',
    'M.A.M. College of Engineering and Technology',
    'K Ramakrishnan College of Engineering (Autonomous)',
    'Indra Ganesan College of Engineering',
    'Parisutham Institute of Technology and Science',
    'CARE College of Engineering',
    'M R K Institute of Technology',
    'Shivani Engineering College',
    'Imayam College of Engineering',
    'Mother Terasa College of Engineering and Technology',
    'Vandayar Engineering College',
    'Annai College of Engineering and Technology',
    'Vetri Vinayaha College of Engineering and Technology',
    'Sri Bharathi Engineering College for Women',
    'Mahath Amma Institute of Engineering and Technology (MIET)',
    'As-Salam College of Engineering and Technology',
    'Meenakshi Ramaswamy Engineering College',
    'Sembodai Rukmani Varatharajan Engineering College',
    'St. Anne\'s College of Engineering and Technology',
    'Kings College of Engineering',
    'Mount Zion College of Engineering and Technology',
    'Shanmuganathan Engineering College',
    'Sudharsan Engineering College',
    'M N S K College of Engineering',
    'Chendhuran College of Engineering and Technology',
    'Anna University Regional Campus - Tirunelveli',
    'University College of Engineering Nagercoil',
    'University V.O.C. College of Engineering',
    'Thamirabharani Engineering College',
    'Rohini College of Engineering & Technology',
    'Stella Mary\'s College of Engineering',
    'Universal College of Engineering and Technology',
    'Renganayagi Varatharaj College of Engineering',
    'Lourdes Mount College of Engineering and Technology',
    'Ramco Institute of Technology',
    'AAA College of Engineering and Technology',
    'Good Shepherd College of Engineering and Technology',
    'V V College of Engineering',
    'Sethu Institute of Technology (Autonomous)',
    'Sun College of Engineering and Technology',
    'Maria College of Engineering and Technology',
    'MAR Ephraem College of Engineering & Technology',
    'M E T Engineering College',
    'Grace College of Engineering',
    'St. Mother Theresa Engineering College',
    'Holy Cross Engineering College',
    'A.R College of Engineering and Technology',
    'Sivaji College of Engineering and Technology',
    'Unnamalai Institute of Technology',
    'Satyam College of Engineering and Technology',
    'Arunachala College of Engineering for Women',
    'D M I Engineering College',
    'PSN Institute of Technology and Science',
    'C S I Institute of Technology',
    'CAPE Institute of Technology',
    'Dr. Sivanthi Aditanar College of Engineering',
    'Francis Xavier Engineering College (Autonomous)',
    'Jayamatha Engineering College',
    'Jayaraj Annapackiam CSI College of Engineering',
    'Kamaraj College of Engineering and Technology (Autonomous)',
    'Mepco Schlenk Engineering College (Autonomous)',
    'Nellai College of Engineering',
    'National Engineering College (Autonomous) Kovilpatti',
    'PSN College of Engineering and Technology (Autonomous)',
    'P S R Engineering College (Autonomous)',
    'PET Engineering College',
    'S Veerasamy Chettiar College of Engineering and Technology',
    'Sardar Raja College of Engineering',
    'SCAD College of Engineering and Technology',
    'Sree Sowdambika College of Engineering',
    'St. Xavier\'s Catholic College of Engineering',
    'AMRITA College of Engineering and Technology',
    'Government College of Engineering Tirunelveli',
    'Dr. G U Pope College of Engineering',
    'Infant Jesus College of Engineering',
    'Narayanaguru College of Engineering',
    'Udaya School of Engineering',
    'Arul Tharum VPMM College of Engineering and Technology',
    'Einstein College of Engineering',
    'Ponjesly College of Engineering',
    'Vins Christian College of Engineering',
    'Lord Jegannath College of Engineering and Technology',
    'Marthandam College of Engineering & Technology',
    'Noorul Islam College of Engineering and Technology',
    'PSN Engineering College',
    'Bethlahem Institute of Engineering',
    'Loyola Institute of Technology and Science',
    'J P College of Engineering College',
    'P.S.R.R College of Engineering',
    'Sri Vidya College of Engineering and Technology',
    'Mahakavi Bharathiyar College of Engineering and Technology',
    'Annai Vailankanni College of Engineering',
    'Thiagarajar College of Engineering',
    'Government College of Engineering',
    'Anna University Regional Campus',
    'Central Electrochemical Research Institute',
    'University College of Engineering Ramanathapuram',
    'University College of Engineering Dindigul',
    'Sri Raajaraajan College of Engineering & Technology',
    'SSM Institute of Engineering and Technology',
    'Vaigai College of Engineering',
    'Karaikudi Institute of Technology',
    'Mangayarkarasi College of Engineering',
    'Jainee College of Engineering and Technology',
    'Christian College of Engineering and Technology',
    'N P R College of Engineering and Technology (Autonomous)',
    'SRM Madurai College for Engineering and Technology',
    'Veerammal Engineering College',
    'R V S Educational Trust\'s Groups of Institutions',
    'Nadar Saraswathi College of Engineering and Technology',
    'Alagappa Chettiar Government College of Engineering and Technology (Autonomous)',
    'Bharath Niketan Engineering College',
    'K L N College of Engineering (Autonomous)',
    'Mohamed Sathak Engineering College',
    'P S N A College of Engineering and Technology (Autonomous)',
    'P T R College of Engineering and Technology',
    'Pandian Saraswathi Yadav Engineering College',
    'R V S College of Engineering',
    'Solamalai College of Engineering',
    'SACS-M A V M M Engineering College',
    'St. Michael College of Engineering and Technology',
    'Syed Ammal Engineering College',
    'Ganapathy Chettiar College of Engineering and Technology',
    'SBM College of Engineering and Technology',
    'Fatima Michael College of Engineering and Technology',
    'Ultra College of Engineering and Technology',
    'Velammal College of Engineering and Technology (Autonomous)',
    'Theni Kammavar Sangam College of Technology',
    'Latha Mathavan Engineering College',
    'Other'
];

// Event Admin Email Mappings (for reference)
// These must match the 'event_admins' collection in Firebase
export const EVENT_ADMIN_EMAILS: { email: string; eventName: string }[] = [
    // Technical Events
    { email: 'pixelreforge@zorphix.com', eventName: 'PixelReforge' },
    { email: 'promptcraft@zorphix.com', eventName: 'PromptCraft' },
    { email: 'algopulse@zorphix.com', eventName: 'AlgoPulse' },
    { email: 'codeback@zorphix.com', eventName: 'codeback' },
    { email: 'siptosurvive@zorphix.com', eventName: 'SiptoSurvive' },
    { email: 'codecrypt@zorphix.com', eventName: 'CodeCrypt' },
    { email: 'linklogic@zorphix.com', eventName: 'LinkLogic' },
    { email: 'pitchfest@zorphix.com', eventName: 'Pitchfest' },

    // Paper Presentation
    { email: 'thesisprecised@zorphix.com', eventName: 'thesisprecised' },

    // Workshops
    { email: 'fintech@zorphix.com', eventName: 'FinTech' },
    { email: 'wealthx@zorphix.com', eventName: 'WealthX' },

    // On-Spot Registration Desk
    { email: 'onspot@zorphix.com', eventName: '' },

    // Master Admin (has access to all events)
    { email: 'admin@zorphix.com', eventName: 'ALL' },
];

// Get all unique event names
export const ALL_EVENTS = [
    'Pixel Reforge',
    'PromptCraft',
    'AlgoPulse',
    'Code Back',
    'Sip to Survive',
    'CodeCrypt',
    'LinkLogic',
    'Pitchfest',
    'Thesis Precised',
    'FinTech 360°',
    'WealthX'
];

// Paid events list
export const PAID_EVENTS = ['FinTech', 'WealthX', 'Thesis Precised'];
